### Create a new patient entity
POST http://localhost:4004/api/patients
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "name": "Dibyabrata Panja-Kafka",
  "email": "test19@example.com",
  "address": "Police Line, Burdwan",
  "dateOfBirth": "2001-06-24",
  "registeredDate": "2025-04-15"
}

###